### ISSUE TITLE
Does not work on Focal Fossa (Ubuntu 20.04)

### ISSUE THREAD

**Issue by omertuc** [MicrosoftDocs/azure-docs-cli#1955]
Does not work on Focal Fossa (Ubuntu 20.04)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by omertuc** [comment]
I tried running this command:
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
And got the following error:
The repository 'https://packages.microsoft.com/repos/azure-cli focal Release' does not have a Release file.

**Comment by omertuc** [comment]
Here is how I fixed it myself for now (worked for my use-case, can't guarantee it's perfect):
First download the script without running it:
curl -sL https://aka.ms/InstallAzureCLIDeb > install_azcli.sh
chmod +x install_azcli.sh

Now modify the line that starts with CLI_REPO=... to look like this:
CLI_REPO=eoan

Save the file

Run ./install_azcli.sh

Good luck

**Comment by MonikaReddy-MSFT** [comment]
@omertuc , Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@omertuc , 
Thanks again for bringing this to our attention. 
I have raised an issue in PG CLI Repo and they will be looking at it and update the doc accordingly. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by pankaj-pal** [comment]
@MonikaReddy-MSFT it seems repo is still not added for focal and the script is focal. Though changing the release to eoan works, but the repo should have be updated.

**Comment by MonikaReddy-MSFT** [comment]
@pankaj-pal - Focal package released for azure-cli 2.6.0. Please try again.
